runtime: nodejs16
service: webpod-api

env_variables:
  SPOTIFY_CLIENT_ID: 8848c71f339348a3bda7228467d547e2
  SPOTIFY_CLIENT_SECRET: 045148c2a6b143db88d7caa87a13e810
  NODE_ENV: Production
  BACKEND_URL: https://webpod-api.kylekerlew.com
  FRONTEND_URL: https://webpod.kylekerlew.com
